mode: rule
tcp-concurrent: true
unified-delay: true

external-controller: "127.0.0.1:9090"

geo-auto-update: true
geo-update-interval: 8
geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"

profile:
  store-selected: true
  store-fake-ip: true





tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address: ["192.168.193.0/24", "172.16.3.0/24"]
  exclude-uid: [35]
  dns-hijack:
    - any:53
    - tcp://any:53

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"


proxies:
  - name: "tor"
    type: socks5
    server: "127.0.0.1"
    port: 9050
  - name: "direct"
    type: direct
    udp: true

proxy-groups:
  - name: Proxy
    type: select
    include-all-proxies: true
    udp: true


dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: whitelist
  fake-ip-filter: 
    - "geosite:gfw"
  respect-rules: true
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - tls://8.8.8.8
    - tls://8.8.4.4

  direct-nameserver:
    - system
    - https://223.5.5.5/dns-query

  nameserver:
    - system
    - https://223.5.5.5/dns-query

  nameserver-policy:
    "geosite:gfw":
      - https://dns.google/dns-query
      - https://security.cloudflare-dns.com/dns-query
      - quic://dns.adguard-dns.com





rules:

  - GEOIP,lan,DIRECT,no-resolve

  - GEOSITE,category-ads-all,REJECT

  
  - DOMAIN-KEYWORD,ghproxy,DIRECT
  - DOMAIN-SUFFIX,bing.com,DIRECT

  - GEOSITE,private,DIRECT
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT,no-resolve


  - MATCH,Proxy


