mode: rule
tcp-concurrent: true
unified-delay: true

geo-auto-update: true
geo-update-interval: 8
geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address: ["192.168.193.0/24", "172.16.3.0/24"]
  dns-hijack:
    - any:53
    - tcp://any:53

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"


proxies:
  - name: "tor"
    type: socks5
    server: "127.0.0.1"
    port: 9050
  - name: "direct"
    type: direct
    udp: true
    interface-name: wlo0


dns:
  enable: true
  prefer-h3: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  respect-rules: true
  nameserver:
    - https://dns.google/dns-query#PROXY
    - https://security.cloudflare-dns.com/dns-query#PROXY
    - quic://dns.adguard-dns.com

  nameserver-policy:
    "geosite:private,onedrive,microsoft@cn,apple,category-games@cn,cn":
      - system
      - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query



rules:

  - GEOIP,lan,DIRECT,no-resolve

  - GEOSITE,category-ads-all,REJECT

  - GEOSITE,private,DIRECT
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,CN,DIRECT,no-resolve

  - GEOSITE,gfw,PROXY

  - MATCH,auto


